# Generated by Django 3.2.11 on 2022-01-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('iswc', 'proprietary_id')},
        ),
        migrations.AlterIndexTogether(
            name='work',
            index_together={('iswc', 'proprietary_id')},
        ),
    ]
