# Generated by Django 3.2.11 on 2022-01-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_auto_20220105_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='repertoire.file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
