# Generated by Django 3.2.11 on 2022-01-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_auto_20220107_1715'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('iswc', 'source')},
        ),
        migrations.AlterIndexTogether(
            name='work',
            index_together={('iswc', 'source')},
        ),
    ]
